Feature/created toolbar and headline section
Braingenius2/Portfolio-website pull request #2
Opened 2023-03-30 13:50 UTC by Braingenius2

# Create toolbar and headline section features
In this pull request, I

- Built the first 2 sections of a personal portfolio site using template 3 from Microverse figma templates.
- Used flexbox in all 2 sections. 
- Added images and backgrounds to enhance the look of the website.
- Made the website responsive, following these breakpoints:
    - Minimum mobile screen size of 375px
    - Minimum desktop screen size of 768px
- Used responsive values in my CSS, like percentages (i.e. width: 80%), instead of pixels

2023-03-30 14:21 UTC, mckent05 requested changes
Hi @Braingenius2, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Your portfolio looks good, well done 👏 👏 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 14:21 UTC, mckent05 commented on styles.css
> +    background-image: url(/images/background1.png);
- I currently cannot see this background image on your project becuase you are navigating into the `images` dir, wrongly. Please start the url with a `.` i.e `./images/background1.png`. Please fix this 🙏 

Your project:
![wrgawrg](https://user-images.githubusercontent.com/73607512/228863179-76c455e7-7ed5-4a9c-b245-b6e87fb69d72.PNG)

2023-03-30 14:21 UTC, mckent05 commented on index.html
> +            <div class="disabled"><img src="images/disabled.png" alt=""></div>
- good job done so far, but the margin between your social icons and the img below is quite much, I have marked it with the blue arrow in the image below. Please fix this 🙏 
![wrgawrg](https://user-images.githubusercontent.com/73607512/228865043-bd862407-aba6-4f0b-a731-9addc3a531d3.PNG)

2023-03-30 21:53 UTC, adel-gu requested changes
# Status: REQUIRED CHANGES ♻️ 

**Hi @Braingenius2 👋🏼** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![](https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47528e7kyhhvr67kj5y225uk1mfjio2cnnytm4ndje&rid=giphy.gif&ct=g)

 ## Highlights
- The background image for the headline section is been added ✔️ 
- The Project is using HTML semantics perfectly ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 21:53 UTC, adel-gu commented on README.md
> +
### This PR should be invalidated ❌  but for consistency's sake and by following the review flow Please consider the following:

- Kindly consider adding the `Future Features` 👌🏼 to the README file the only optional header in the documentation is the **FAQ** section 👍🏼 .

2023-03-30 21:53 UTC, adel-gu commented on README.md
> +<!-- AUTHORS -->
- **[OPTIONAL]** Please consider adding a detailed description on how this repo should be used and consider readers that are non-technical 👍🏼

2023-03-30 21:53 UTC, adel-gu commented on README.md
> +This project is [MIT](./LICENSE.md) licensed.
- **[OPTIONAL]** Sorry this wasn't mentioned before but it's highly recommended so please consider fixing the license link because it is currently broken, that's because the file `LICENSE.md` is not found in your project so please rename the current `LICENSE` in the root to `LICENSE.md` 💪🏼

2023-03-30 21:53 UTC, adel-gu commented on styles.css
> +  }
### Well done Adding the background image to the headline section and also fixing the spacing between the social icons and the next image 👏🏼 👏🏼 👏🏼  However there is still room for improvement 👍🏼 

- [ ]  Currently the background image it's not responsive to mobile different screens, please be aware of mobile screen sizes are varies in the range of **min 375px** and **max 786px**  so kindly fix its position so it will look the same as in the Figma design as much as possible.

### Your Design
![image](https://user-images.githubusercontent.com/68030297/228970524-5488f2b5-d72b-4550-9c6a-4a56a5605b93.png)


### Figma Design
![Screenshot from 2023-03-30 22-39-20](https://user-images.githubusercontent.com/68030297/228970685-e713827d-be59-42a1-a44d-e5c8edb9d17d.png)

### Suggestions 
- This is can be easily achieved if you imported each piece of the decoration image **highlighted in red from the above screenshot** on its own and then set multiple background images to the headline section, each decoration image in its own position 😎.

Follow [CSS Multiple Backgrounds](https://www.w3schools.com/css/css3_backgrounds.asp) for information about how you can set multiple image backgrounds 👍🏼

2023-03-30 21:53 UTC, adel-gu commented on styles.css
> +  }
### **[OPTIONAL]** Suggestions:

-  Sorry this wasn't mentioned in the previous review, kindly adjust the title and the subtitle sizes so it looks the same as the Figma design 👌🏼 

Duplicating the Figma design as much as possible it is really the project's purpose, to practice HTML and CSS 👍🏼 

### Your Design 
![Screenshot from 2023-03-30 22-44-22](https://user-images.githubusercontent.com/68030297/228971978-757e79e0-ea3b-41f2-96cb-5d137f714d33.png)

### Figma Design
![Screenshot from 2023-03-30 22-48-19](https://user-images.githubusercontent.com/68030297/228972035-f4bce447-3414-46b8-9cd3-e0b892c272c7.png)

2023-03-31 11:32 UTC, Tufahel approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @Braingenius2 :wave: 
 
Well done 👍 on implementing the `required` as well as the `optional` changes. Your project is complete now!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 👏🏻

![](https://media0.giphy.com/media/d31w24psGYeekCZy/giphy.gif?cid=ecf05e47zaer8jfqmid0gfxhz2oq4gcjqy2c2aol3ldn6gvl&rid=giphy.gif&ct=g)

:heavy_check_mark: Linter checks are passing.
:heavy_check_mark: Readme is professional.
:heavy_check_mark: Commit messages are professional.


## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 11:51 UTC, merged