Feature/middle section works about me
Braingenius2/Portfolio-website pull request #3
Opened 2023-04-01 18:08 UTC by Braingenius2

# Add middle sections to portfolio site: Works and About me
In this pull request, I

- Built Works section using CSS grid and flexbox layout tools
- Built About me section using a flexbox layout
- Added additional background images in the About me section.
- Implemented the button interactions (enable, hover, etc.).

2023-04-01 18:20 UTC, Trast00 reviewed
Hi @Braingenius2 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that have failing linter errors. Please fix the linter before ask for a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@Trast00) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-01 19:32 UTC, divinecharlotte requested changes
Hi @Braingenius2       , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 


- Descriptive PR ✔️
- linters are passing 👍  
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] in your readme file kindly consider adding working links for the following : your Linkdhin account in authors section; real issue page on the contributing section
 to give a god user experience to the person visiting your readme

_Check the comments under the review._



## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 19:32 UTC, divinecharlotte commented on index.html
> +        <section id="works">
- [ ] i can see that you used flexbox to align this sections content thats also good but its not meeting  the below requirement
> The main container of the projects has a display:grid
kindly consider changing the `display:flex` to `display:grid ` to full-fill that requirement

2023-04-01 19:32 UTC, divinecharlotte commented on index.html
> +                        </ul>
- [ ] kindly consider making sure that you stick to the figma design as much as possible please put all there li's on the same line to have your card look like the one in the figma design 
- your design 👇 
<img width="431" alt="Screen Shot 2023-04-01 at 21 21 10" src="https://user-images.githubusercontent.com/60146030/229310207-da5a2f6f-7f74-4355-97fc-5ef117718962.png">


- given design 👇 
<img width="332" alt="Screen Shot 2023-04-01 at 21 21 47" src="https://user-images.githubusercontent.com/60146030/229310230-c7022b3b-909c-467d-a827-fc1df1d14bab.png">

2023-04-01 19:32 UTC, divinecharlotte commented on index.html
> +            </div>
- [ ] good implementation of this div but it still missing something which is the background image kindly consider adding that to implement exactly this section as expected

2023-04-01 19:32 UTC, divinecharlotte commented on index.html
> +                            <li>API Design</li>
- [ ] kindly consider adding the technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li` to fullfill the below requirement 👇 
- > The technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`

2023-04-02 01:01 UTC, Braingenius2 commented on index.html
> +            <div class="card-work-row">
@divinecharlotte If you check well you'd see I used `display: grid ` in the container card-work-row containing all the cards which is the actual core requirement of the project. 
![image](https://user-images.githubusercontent.com/37679347/229324837-6ea64afb-25de-413a-8d2f-c668f1636c43.png)

2023-04-02 04:30 UTC, Shedrack-Sunday requested changes
Hi @KALUNGI-J-BOBSON        👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlight
✔️ good PR summary
✔️ Moderate UI
  
# Required Changes ♻️

- [x] I must admit you have really put in the effort so far in this project, however, the changes required below need to be implemented :
- A few styling adjustments are needed👏

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-02 04:30 UTC, Shedrack-Sunday commented on index.html
> +                <button class="get-resume" type="button">Get my resume</button>
- [ ] As stated by the previous reviewer, you're missing the background images of the about section. I've made detailed comparison below for you to see. This is important to stay t user requirements, as would be so in the future with clients, and give a better UX.
- Please place them appropriately 

## Your design:
![image](https://user-images.githubusercontent.com/50990925/229331329-24e28bca-2ebf-4d05-ba21-52a25e957d44.png)

## Figma:
![image](https://user-images.githubusercontent.com/50990925/229331356-354a6462-4e69-42b1-a2e6-7ede3c9599cc.png)

2023-04-02 05:42 UTC, didierganthier approved these changes
Hi @Braingenius2 ,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

<img src="https://media.giphy.com/media/l9CSJHK88kMTe/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

2023-04-02 05:44 UTC, merged