Feature/created desktop version
Braingenius2/Portfolio-website pull request #7
Opened 2023-04-08 01:25 UTC by Braingenius2

# Create a desktop version using RWD
In this pull request, I

- Used media queries to make sure that the portfolio website displays correctly on desktop screens.
- lay out the elements on the page using Grid and Flexbox.
- Made the website responsive, following these breakpoints:
    - Minimum mobile screen size of 375px
    - Minimum desktop screen size of 768px
- Used responsive values in my CSS, like percentages (i.e. width: 80%), instead of pixels

2023-04-08 02:16 UTC, adel-gu requested changes
# Status: REQUIRED CHANGES ♻️ 
**Hi @Braingenius2  👋🏼** 

Good job so far! 👏🏼👏🏼👏🏼 however, there are some issues that you still need to work on to go to the next project but you are almost there! 💪🏼💪🏼💪🏼. 

![](https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47gehzel12kjeptl427bdnj4gfo7gttvq5y7i4y9b6&rid=giphy.gif&ct=g)

## Highlights
- Used the correct media query ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-08 02:16 UTC, adel-gu commented on styles.css
> +    background-image: url(./images/illustration-about-me-2-desktop.png), url(./images/frame-about-me.png);
- [ ] At the width `984px` the skill cards are overlapping and that's because most of the element has a fixed height that has been set to them, so kindly avoid setting any fixed height and let the browser decide to that based on the content size  👍🏼 this will help you achieve responsive website so easily.

### Your Design
![image](https://user-images.githubusercontent.com/68030297/230698648-c2270110-574e-49e6-a667-91523c85d668.png)

### Figma Design
![Screenshot from 2023-04-08 03-08-34](https://user-images.githubusercontent.com/68030297/230698663-83e38dc7-ac98-4d04-a1e5-9db549c99d99.png)

2023-04-08 02:16 UTC, adel-gu commented on styles.css
> +button {
- [ ] Please consider duplicating the exact same style from the Figma design as much as possible 💯 currently all the buttons are diverted from the required design, try adding `border: none` you will start getting some results and then add the necessary interactions as shown from the Design system.

### Your Design
![Screenshot from 2023-04-08 03-11-06](https://user-images.githubusercontent.com/68030297/230698891-a71454c4-a258-4bb2-b083-bcbe7607a56a.png)

### Figma Design
![Screenshot from 2023-04-08 03-15-04](https://user-images.githubusercontent.com/68030297/230698906-a4d00b7e-af1c-464b-8073-240999cb2df4.png)

2023-04-09 01:38 UTC, didierganthier approved these changes
Hi @Braingenius2 ,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

<img src="https://media.giphy.com/media/l9CSJHK88kMTe/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Optional Suggestions 💡
- N/A

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

2023-04-09 01:54 UTC, merged